# Copyright 2023 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

stages:
  - sim

variables:
  VSIM: "questa-2025.1-dz vsim"
  VCS: "vcs-2024.09-zr vcs"
  VLOGAN: "vcs-2024.09-zr vlogan"

sim:
  stage: sim
  script:
    - make all_vsim

sim-vcs:
  stage: sim
  script:
    - make all_vcs
